--smallest name
SELECT CITY, LENGTH(CITY) AS LENGTH
FROM STATION
WHERE LAT_N > 0 AND LONG_W > 0
ORDER BY LENGTH(CITY), CITY
FETCH FIRST 1 ROWS ONLY;

--largest name
SELECT CITY, LENGTH(CITY) AS LENGTH
FROM STATION
WHERE LAT_N > 0 AND LONG_W > 0
ORDER BY LENGTH(CITY) DESC, CITY
FETCH FIRST 1 ROWS ONLY;
